Adding in approvals

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -106,6 +106,98 @@ commands:
               done
             done
 
+  approve_jobs:
+    parameters:
+      job-names:
+        description: A list of comma separated hold jobs to approve
+        type: string
+      run-on-branch:
+        description: |
+          The branches to actually wait on. By default this waits on all branches. If set to anything but
+          '*' the wait will run only on the specified branch
+        type: string
+        default: "*"
+      kill-gracefully:
+        description: If true it completes and lets future steps continue
+        type: string
+        default: "true"
+
+    steps:
+      - run:
+          name: Swissknife - Approve On Hold Job by Name
+          command: |
+            if [ -z "$BASH" ]; then
+              echo Bash not installed.
+              exit 1
+            fi
+            hash jq 2>/dev/null || { echo >&2 "jq is not installed.  Aborting."; exit 1; }
+            if [[ "$CIRCLE_TOKEN" == "" ]]; then
+              echo "CIRCLE_TOKEN not set. Set a token to access the circle API in the env var CIRCLE_TOKEN";
+              exit 1;
+            fi
+
+            if [[ "<< parameters.run-on-branch >>" != "*" && "<< parameters.run-on-branch >>" != "$CIRCLE_BRANCH" ]]; then
+              echo "Chosen to run only on << parameters.run-on-branch >> and currently we are on $CIRCLE_BRANCH, exiting";
+              exit 0;
+            fi
+
+            mkdir -p /tmp/swissknife
+
+
+            get_job_id_and_type() {
+              local NAME_OF_JOB="$1"
+              local ID=""
+
+              curl --header 'Circle-Token: $CIRCLE_TOKEN' -f -s https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job > /tmp/swissknife/wf_$CIRCLE_WORKFLOW_ID.json
+              ID=$(jq -r ".items[] | select(.name==\"${NAME_OF_JOB}\") | .id" /tmp/swissknife/wf_$CIRCLE_WORKFLOW_ID.json)
+              TYPE=$(jq -r ".items[] | select(.name==\"${NAME_OF_JOB}\") | .id" /tmp/swissknife/wf_$CIRCLE_WORKFLOW_ID.json)
+              echo "${ID} ${TYPE}"
+            }
+
+
+            job_list="<< parameters.job-names >>"
+
+            for job_name in ${job_list//,/ }
+            do
+              # Reset job id and job type
+              job_id=""
+              job_type=""
+
+              echo "Checking type of ${job_name}...."
+
+              read job_id job_type < <(get_job_id_and_type ${job_name})
+              if [[ "$job_type" == "approval" ]]; then
+                echo "${job_name} is an approval job!"
+                echo "Moving onto approval...."
+                status_code=$(curl --write-out %{http_code} --silent --output /dev/null --request POST "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/approve/${job_id}" --header "Circle-Token: ${CIRCLE_TOKEN}")
+
+                if [[ "$status_code" -eq 200 ]] ; then
+                  echo "${job_name} has been approved!"
+                else
+                  echo "Something went wrong! Status Code: ${status_code}"
+                  if [[ "<< parameters.kill-gracefully >>" == "true" ]]; then
+                    echo "Proceeding with future steps";
+                    break
+                  else
+                    echo "Failing job by exiting forcefully";
+                    exit 1;
+                  fi
+                fi
+              else
+                echo "${job_name} is NOT approval job!"
+                if [[ "<< parameters.kill-gracefully >>" == "true" ]]; then
+                  echo "Proceeding with future steps";
+                  break
+                else
+                  echo "Failing job by exiting forcefully";
+                  exit 1;
+                fi
+              fi
+            done
+
+
+
+
 jobs:
   build_1:
     docker:
@@ -132,17 +224,15 @@ jobs:
       - run:
           name: Sleeping for 60 secs
           command: echo "Sleeping for 60 secs" && sleep 60
-      - run:
-          name: Store Results in Workspace
-          command: echo "Store the results somewhere."
-          when: always
+      - approve_jobs:
+          job-names: "manual-approval"
 
   upload_results:
     docker:
       - image: cimg/base:2022.04
     steps:
       - wait_for_jobs:
-          job-names: "build_2"
+          job-names: "build_2,build_1"
       - run:
           name: Persist Workspace with Results
           command: echo "Attach Workspace......"
@@ -158,3 +248,9 @@ workflows:
       - build_2
       - upload_results:
           name: "Upload Android App Build Logs"
+      - manual-approval:
+          type: approval
+      - upload_results:
+          name: "Upload Android App Build Logs with Approval"
+          requires:
+            - manual-approval
